import { MaangWeek } from '../types';

export const INITIAL_MAANG_WEEKS: MaangWeek[] = [
  {
    id: 'maang-week-1',
    weekNumber: 1,
    dateRange: 'Aug 24 – Aug 30',
    phase: 1,
    phaseTitle: 'Phase 1: Foundations & Algorithmic Patterns',
    status: 'in_progress',
    jsSystemDesignFocus: 'Execution Context, Call Stack, Event Loop, Macro/Microtask queues, Scope & Closures.',
    dsaMasteryFocus: 'Time & Space Complexity (Big O), Pattern 1: Sliding Window, Pattern 2: Two Pointers, Pattern 4: Merge Intervals, Pattern 5: Cyclic Sort.',
    deliverables: [
      { id: 'w1-d1', text: 'Arrays & Strings: 10 Easy, 10 Medium', completed: false },
      { id: 'w1-d2', text: 'Master Patterns 1, 2, 4, & 5: 10 Medium', completed: false },
    ],
    weeklyReviewCheck: 'Re-solve every single problem you needed hints for without looking at the solution.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Arrays/Strings)',
      saturday: 'Sat: 3hrs System Design',
      sunday: 'Sun: 2hrs Review & Mock',
    },
  },
  {
    id: 'maang-week-2',
    weekNumber: 2,
    dateRange: 'Aug 31 – Sep 6',
    phase: 1,
    phaseTitle: 'Phase 1: Foundations & Algorithmic Patterns',
    status: 'pending',
    jsSystemDesignFocus: 'Prototypal Inheritance, Object composition, V8 engine memory management & garbage collection.',
    dsaMasteryFocus: 'Singly Linked Lists, Doubly Linked Lists, Pattern 3: Fast & Slow Pointers, Pattern 6: In-place Reversal of a LinkedList.',
    deliverables: [
      { id: 'w2-d1', text: 'Linked Lists: 5 Easy, 15 Medium', completed: false },
      { id: 'w2-d2', text: 'Master Patterns 3 & 6', completed: false },
    ],
    weeklyReviewCheck: 'Code a clean, complete custom Linked List implementation in plain text editor with no IDE.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Linked Lists)',
      saturday: 'Sat: 3hrs System Design',
      sunday: 'Sun: 2hrs Custom List Implementation',
    },
  },
  {
    id: 'maang-week-3',
    weekNumber: 3,
    dateRange: 'Sep 7 – Sep 13',
    phase: 1,
    phaseTitle: 'Phase 1: Foundations & Algorithmic Patterns',
    status: 'pending',
    jsSystemDesignFocus: 'Deep dive into Promises, Async/Await internals, Custom Promise implementation, and Polyfills.',
    dsaMasteryFocus: 'Stacks, Queues, Monotonic Stacks, and Queue implementation using stacks. Pattern 11: Modified Binary Search.',
    deliverables: [
      { id: 'w3-d1', text: 'Stacks & Queues: 5 Easy, 15 Medium', completed: false },
      { id: 'w3-d2', text: 'Master Pattern 11: Modified Binary Search', completed: false },
    ],
    weeklyReviewCheck: 'Write polyfills for Promise.all and Array.prototype.map completely from scratch.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Stacks/Queues)',
      saturday: 'Sat: 3hrs System Design',
      sunday: 'Sun: 2hrs Polyfill Deep Dive',
    },
  },
  {
    id: 'maang-week-4',
    weekNumber: 4,
    dateRange: 'Sep 14 – Sep 20',
    phase: 1,
    phaseTitle: 'Phase 1: Foundations & Algorithmic Patterns',
    status: 'pending',
    jsSystemDesignFocus: 'Functional programming in JS, Currying, Memoization, Debounce/Throttle implementations.',
    dsaMasteryFocus: 'Binary Trees, Binary Search Trees (BST), Pattern 7: Tree Breadth First Search, Pattern 8: Tree Depth First Search.',
    deliverables: [
      { id: 'w4-d1', text: 'Trees & BST: 5 Easy, 15 Medium', completed: false },
      { id: 'w4-d2', text: 'Master Patterns 7 & 8', completed: false },
      { id: 'w4-d3', text: 'Phase 1 Checkpoint: Crack a random Medium under 35 mins', completed: false },
    ],
    weeklyReviewCheck: 'Re-verify speed matrix. Code all 4 tree traversals recursively and iteratively without debugging tools.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Trees)',
      saturday: 'Sat: 3hrs System Design',
      sunday: 'Sun: 2hrs Speed Matrix Review',
    },
  },
  {
    id: 'maang-week-5',
    weekNumber: 5,
    dateRange: 'Sep 21 – Sep 27',
    phase: 2,
    phaseTitle: 'Phase 2: Scalable Systems & Intermediate Algorithms',
    status: 'pending',
    jsSystemDesignFocus: 'System Design Building Blocks & AI Infrastructure: Load Balancers, Caching, CDNs. AI Model Serving Architecture (vLLM, Ray), Latency/Throughput trade-offs.',
    dsaMasteryFocus: "Pattern 9: Two Heaps, Pattern 13: Top 'K' Elements, Pattern 14: K-way merge, Hashing algorithms, and Hash Map collision handling mechanics.",
    deliverables: [
      { id: 'w5-d1', text: "Heaps & Top 'K' Elements: 10 Medium", completed: false },
      { id: 'w5-d2', text: 'Hash Maps / Sets: 10 Medium', completed: false },
      { id: 'w5-d3', text: 'Master Patterns 9, 13, & 14', completed: false },
    ],
    weeklyReviewCheck: 'System Design Case Study: Document and sketch the complete scale architecture for a global Video Streaming Service (Netflix).',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Heaps/Hashing)',
      saturday: 'Sat: 3hrs System Design (Netflix Case)',
      sunday: 'Sun: 2hrs Architecture Sketching',
    },
  },
  {
    id: 'maang-week-6',
    weekNumber: 6,
    dateRange: 'Sep 28 – Oct 4',
    phase: 2,
    phaseTitle: 'Phase 2: Scalable Systems & Intermediate Algorithms',
    status: 'pending',
    jsSystemDesignFocus: 'Database Architecture & ML Data Pipelines: SQL/NoSQL, Sharding, Consistent Hashing. Vector Databases (Pinecone, Milvus), Feature Stores, Streaming Data Pipelines.',
    dsaMasteryFocus: 'Graphs representations (Adjacency Matrix & List), Depth-First Search (DFS), Breadth-First Search (BFS), Pattern 16: Topological Sort (Graph).',
    deliverables: [
      { id: 'w6-d1', text: 'Graphs (BFS/DFS): 15 Medium Problems', completed: false },
      { id: 'w6-d2', text: 'Master Pattern 16: Topological Sort', completed: false },
    ],
    weeklyReviewCheck: 'System Design Case Study: Design a highly available URL Shortener (TinyURL) handling 10k+ requests/sec.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Graphs)',
      saturday: 'Sat: 3hrs System Design (TinyURL Case)',
      sunday: 'Sun: 2hrs Architecture Sketching',
    },
  },
  {
    id: 'maang-week-7',
    weekNumber: 7,
    dateRange: 'Oct 5 – Oct 11',
    phase: 2,
    phaseTitle: 'Phase 2: Scalable Systems & Intermediate Algorithms',
    status: 'pending',
    jsSystemDesignFocus: 'Front-End System Design & GenAI Integration: Asset delivery, State Management. Integrating RAG workflows, Chatbot UI state, LLM Context Window optimization.',
    dsaMasteryFocus: 'Backtracking fundamental patterns, Pattern 10: Subsets, Pattern 15: 0/1 Knapsack (Dynamic Programming).',
    deliverables: [
      { id: 'w7-d1', text: 'Backtracking & 1D DP: 15 Medium Problems', completed: false },
      { id: 'w7-d2', text: 'Master Patterns 10 & 15', completed: false },
    ],
    weeklyReviewCheck: 'System Design Case Study: Complete end-to-end frontend and state architecture of a complex collaborative editor (Google Docs UI).',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Backtracking/DP)',
      saturday: 'Sat: 3hrs System Design (Google Docs UI)',
      sunday: 'Sun: 2hrs Architecture Sketching',
    },
  },
  {
    id: 'maang-week-8',
    weekNumber: 8,
    dateRange: 'Oct 12 – Oct 18',
    phase: 2,
    phaseTitle: 'Phase 2: Scalable Systems & Intermediate Algorithms',
    status: 'pending',
    jsSystemDesignFocus: 'Communication Protocols & AI Reliability: gRPC, WebSockets, Web Security. Agentic System Design, Handling Tool-Use failures, AI Infrastructure Reliability, Model Monitoring.',
    dsaMasteryFocus: '2D Matrices, Island isolation problems, advanced graph cycle detection, Pattern 12: Bitwise XOR.',
    deliverables: [
      { id: 'w8-d1', text: 'Matrix / Miscellaneous complex patterns: 15 Medium Problems', completed: false },
      { id: 'w8-d2', text: 'Master Pattern 12: Bitwise XOR', completed: false },
    ],
    weeklyReviewCheck: 'System Design Case Study: Architect a highly stable real-time Chat Application backend and client synchronization engine (WhatsApp/Slack).',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Morning DSA (Matrices/Cycles)',
      saturday: 'Sat: 3hrs System Design (Chat App)',
      sunday: 'Sun: 2hrs Architecture Sketching',
    },
  },
  {
    id: 'maang-week-9',
    weekNumber: 9,
    dateRange: 'Oct 19 – Oct 25',
    phase: 3,
    phaseTitle: 'Phase 3: Speed, Behavioral & MAANG Mock Loops',
    status: 'pending',
    jsSystemDesignFocus: 'Web Performance optimization Deep-Dive (Core Web Vitals). Component-driven UI pattern scalability.',
    dsaMasteryFocus: 'Speed Coding Phase: Stop using LeetCode UI. Solve using standard plain text editors without syntax highlights.',
    deliverables: [
      { id: 'w9-d1', text: 'Random Mixed Pattern Grinding: 15 Mediums under strict 30-minute timers', completed: false },
      { id: 'w9-d2', text: 'Instantly map unseen problems to the 16 mastered patterns', completed: false },
    ],
    weeklyReviewCheck: 'System Design Case Study: Complete client-server design for an infinite scroll social news feed with real-time ranking optimization (Facebook Feed).',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Speed Coding (No IDE)',
      saturday: 'Sat: 3hrs System Design (Facebook Feed)',
      sunday: 'Sun: 2hrs Review',
    },
  },
  {
    id: 'maang-week-10',
    weekNumber: 10,
    dateRange: 'Oct 26 – Nov 1',
    phase: 3,
    phaseTitle: 'Phase 3: Speed, Behavioral & MAANG Mock Loops',
    status: 'pending',
    jsSystemDesignFocus: 'Behavioral STAR Mapping: Document stories for Technical Conflict, Failure, Tight Deadlines, and Architecture decisions.',
    dsaMasteryFocus: 'Live verbal articulation. Conduct 3 live coding mock interviews as interviewee and 3 as interviewer via Pramp.',
    deliverables: [
      { id: 'w10-d1', text: 'Re-solve 20 random past medium failures within 30 mins each', completed: false },
      { id: 'w10-d2', text: 'Instantly map problems to the 16 mastered patterns during mocks', completed: false },
    ],
    weeklyReviewCheck: 'Audit behavioral framework mapping. Check if all responses emphasize clear technical trade-offs and business impact metrics.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Behavioral STAR Prep',
      saturday: 'Sat: 3hrs Live Pramp Mocks',
      sunday: 'Sun: 2hrs Error Log Review',
    },
  },
  {
    id: 'maang-week-11',
    weekNumber: 11,
    dateRange: 'Nov 2 – Nov 8',
    phase: 3,
    phaseTitle: 'Phase 3: Speed, Behavioral & MAANG Mock Loops',
    status: 'pending',
    jsSystemDesignFocus: 'System Design Live Mocks: Participate in 4 full-length interactive system architecture mock sessions with external peers.',
    dsaMasteryFocus: 'Edge-case hunting (Null boundaries, Empty collections, Integer pointer overflow reviews).',
    deliverables: [
      { id: 'w11-d1', text: 'Review complete personal historical error log containing all past problem failures', completed: false },
      { id: 'w11-d2', text: 'Solidify mapping to the 16 mastered patterns under stress', completed: false },
    ],
    weeklyReviewCheck: 'Polishing step: Refine leadership narrative to emphasize team mentorship, product scope ownership, and cross-functional influence.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Edge-case hunting',
      saturday: 'Sat: 3hrs Live System Design Mocks',
      sunday: 'Sun: 2hrs Leadership Narrative',
    },
  },
  {
    id: 'maang-week-12',
    weekNumber: 12,
    dateRange: 'Nov 9 – Nov 15',
    phase: 3,
    phaseTitle: 'Phase 3: Speed, Behavioral & MAANG Mock Loops',
    status: 'pending',
    jsSystemDesignFocus: 'Full Loop Simulations: Run 3 complete back-to-back mock cycles containing: 2x DSA loops, 1x System Design, 1x Behavioral.',
    dsaMasteryFocus: 'Cool-down and retention mode. Solve 1-2 light Mediums daily to sustain mental fluency without burning out.',
    deliverables: [
      { id: 'w12-d1', text: 'Optimize Resume highlighting metrics/scale', completed: false },
      { id: 'w12-d2', text: 'Launch multi-channel outbound outreach and target MAANG referrals', completed: false },
    ],
    weeklyReviewCheck: 'Launch! Enter interview loops with high-velocity focus. Crush this.',
    weeklyReviewCompleted: false,
    workerTimetable: {
      weekday: 'Mon-Fri: 1hr Full Loop Simulation',
      saturday: 'Sat: Resume Optimization',
      sunday: 'Sun: Launch Applications!',
    },
  },
];
